#ifndef _ENC28J60BUFFER_H_
#define _ENC28J60BUFFER_H_

#define BUFFERSTART 0x0000
#define BUFFEREND 0x1FFF

#define RXBUFFERSIZE 0x1800

#define RXBUFFERSTPTR BUFFERSTART
#define RXBUFFERNDPTR ( BUFFERSTART + (RXBUFFERSIZE - 1) )

#define TXBUFFERSTPTR (RXBUFFERNDPTR + 1)

#endif